name: Lint CloudFormation Templates

on:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  cloudformation-linter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Cloud Formation Linter with Latest Version
        uses: scottbrenner/cfn-lint-action@v2

      - name: Print the Cloud Formation Linter Version & run Linter.
        run: |
          cfn-lint --version
          cfn-lint -t ./*.y*ml

      - uses: minchao/cfn-nag-action@master
        with:
          args: '--input-path .'
