name: Check CloudFormation Templates for Best Practices

on:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  cloudformation-nagger:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: minchao/cfn-nag-action@master
        with:
          args: '--input-path *.yaml'
