name: Lint Terraform Templates

on:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  terraform-linter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v1
        with:
          tflint_version: v0.27.0

      - name: Show version
        run: tflint --version

      - name: Run TFLint
        run: tflint -f compact

  tfsec:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Terraform SCA
        uses: triat/terraform-security-scan@v2.2.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
